# Generated by Django 3.2.11 on 2022-04-06 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0013_auto_20220407_0850'),
        ('accounts2', '0008_auto_20220117_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='common_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wm.commonsubject'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_category_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
